### ISSUE TITLE
copy aanpassingen

### ISSUE THREAD

**Issue by mondayrunner** [newdesigners/newdesigners.agency#10]
We help MKB to scale their business ipv A student-run digital agency

Tekst eronder:

"Transform your company into a design-led powerhouse with the help of New Designers. We specialize in helping businesses like yours become more attractive and balanced in their media presence, both online and offline. From creating stunning new branding to producing engaging videos, our team of experts will work with you every step of the way to ensure that your company stands out from the competition."

Work with us ipv Submit (mag overal waar de button staat, de button mag ook op meer plekken in de content)
<img width="223" alt="image" src="https://user-images.githubusercontent.com/2202213/226979782-1523fff8-87eb-4e53-aa6c-95902a303560.png">

* form moet dus kleiner, misschien alleen naam en tel of emain in 1 veld. Niemand vult het nu in.

<img width="1553" alt="image" src="https://user-images.githubusercontent.com/2202213/226980125-453eaaa9-8dbb-4908-ac63-d1f92a662fd1.png">

<img width="1518" alt="image" src="https://user-images.githubusercontent.com/2202213/226981735-af0a9c12-370c-4875-bf5f-8d3a97a75fe9.png">

Moet worden:
Branding, Websites, Video

Eronder kan in ander font
from 1500 euro, from 4500, from 3500 euro

Speel ook maar met de iconen, misschien passen ze niet bij het onderwerp

En dan uitleg wat het inhoud. Doe voor nu maar even wat vul text uit chatGPT.

<img width="495" alt="image" src="https://user-images.githubusercontent.com/2202213/226981789-1c0cf375-ce70-4645-8662-a06b7061d68c.png">
Ook even anders, Work with us

En tekst:

Our design and video production services are top-notch, and we take pride in delivering exceptional results for every client we work with. Whether you need a new logo and branding guidelines, a responsive and user-friendly website, or a stunning video that tells your company's story, we've got you covered.

**Comment by KonradZwl** [comment]
Alle wijzigingen doorgevoerd, contact form is nog aan te passen als dit te lang is. Icons bij services zijn aan te passen als deze niet voldoen aan design eisen.
