### ISSUE TITLE
Maak een testimonial block op de homepage 

### ISSUE THREAD

**Issue by mondayrunner** [newdesigners/newdesigners.agency#5]
https://www.figma.com/file/qoYybsF6d45D69iwimltDD/Homepage?node-id=0-1&t=nUmSjnqZ6N5CWXIt-0

Vergeet niet te testen op mobile en je moet daar zelf het design voor doen ;)
<img width="1040" alt="image" src="https://user-images.githubusercontent.com/2202213/226975379-a2930393-00eb-4e97-823e-e7abaad64e21.png">

**Comment by KonradZwl** [comment]
Fixed, hij staat live op development + responsive
